import { Link } from "react-router-dom";
import SEO from "../components/SEO";
import Breadcrumbs, { breadcrumbJsonLd } from "../components/Breadcrumbs";

const TRAIL = [{ label: "Home", path: "/" }, { label: "Farm Tasks" }];

export default function FarmTasks() {
  return (
    <>
      <SEO
        title="Farm Task Management"
        description="Turn farm to-dos into a real task list. FarmFlow lets you set due dates, track status, and mark farm tasks complete as work gets done."
        path="/farm-tasks"
        jsonLd={breadcrumbJsonLd(TRAIL)}
      />
      <Breadcrumbs trail={TRAIL} />

      <header className="page-head container">
        <p className="eyebrow">Farm tasks</p>
        <h1>A task list built around how farm work actually happens</h1>
        <p className="lede">
          Farm work is a mix of scheduled jobs and things that come up
          unexpectedly. FarmFlow's task tracking is deliberately simple —
          a title, an optional description, a due date, and a status — so
          it's fast to add a task in the moment and easy to see what's
          still open.
        </p>
      </header>

      <section className="section">
        <div className="container grid-2">
          <div>
            <h2>Why a dedicated task list beats a notebook</h2>
            <p>
              A paper list works until it's left in the truck, gets rained
              on, or simply falls out of date because yesterday's list
              wasn't crossed off. A digital task list tied to your account
              is available from any device and keeps a record of what got
              done and when.
            </p>
            <p>
              Status tracking — pending, in progress, or complete — makes
              it easy to see at a glance what still needs attention without
              scrolling through everything that's already finished.
            </p>
          </div>
          <div className="card">
            <h3 className="mt-0">What FarmFlow tracks per task</h3>
            <ul className="benefits-list">
              <li>Title</li>
              <li>Description (optional)</li>
              <li>Due date</li>
              <li>Status: pending, in progress, or complete</li>
            </ul>
          </div>
        </div>
      </section>

      <section className="section section-alt">
        <div className="container">
          <h2>Tasks generated by crops and livestock</h2>
          <p style={{ maxWidth: "70ch" }}>
            Many farm tasks trace back to a specific crop or animal —
            harvesting a field from <Link to="/crop-management">crop management</Link>,
            or a health check tied to <Link to="/livestock-management">livestock management</Link>.
            Keeping tasks in the same account as those records, part of the
            full <Link to="/features">feature set</Link>, means nothing has
            to be tracked twice.
          </p>
        </div>
      </section>
    </>
  );
}
